server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /runtime-config.js {
        default_type application/javascript;
        return 200 'window.__API_BASE__="${API_URL}/api";';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
