/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTransmissionRouteImport } from './routes/app/transmission'
import { Route as AppSurveillanceRouteImport } from './routes/app/surveillance'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppScreeningRouteImport } from './routes/app/screening'
import { Route as AppResistanceRouteImport } from './routes/app/resistance'
import { Route as AppPipelinesRouteImport } from './routes/app/pipelines'
import { Route as AppPatientsRouteImport } from './routes/app/patients'
import { Route as AppOutbreaksRouteImport } from './routes/app/outbreaks'
import { Route as AppLabRouteImport } from './routes/app/lab'
import { Route as AppHospitalMapRouteImport } from './routes/app/hospital-map'
import { Route as AppForecastingRouteImport } from './routes/app/forecasting'
import { Route as AppDevicesRouteImport } from './routes/app/devices'
import { Route as AppAlertsRouteImport } from './routes/app/alerts'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppTeamRouteImport } from './routes/app/team'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransmissionRoute = AppTransmissionRouteImport.update({
  id: '/transmission',
  path: '/transmission',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSurveillanceRoute = AppSurveillanceRouteImport.update({
  id: '/surveillance',
  path: '/surveillance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScreeningRoute = AppScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResistanceRoute = AppResistanceRouteImport.update({
  id: '/resistance',
  path: '/resistance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPipelinesRoute = AppPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOutbreaksRoute = AppOutbreaksRouteImport.update({
  id: '/outbreaks',
  path: '/outbreaks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLabRoute = AppLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHospitalMapRoute = AppHospitalMapRouteImport.update({
  id: '/hospital-map',
  path: '/hospital-map',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppForecastingRoute = AppForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/hospital-map': typeof AppHospitalMapRoute
  '/app/lab': typeof AppLabRoute
  '/app/outbreaks': typeof AppOutbreaksRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/pipelines': typeof AppPipelinesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resistance': typeof AppResistanceRoute
  '/app/screening': typeof AppScreeningRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/surveillance': typeof AppSurveillanceRoute
  '/app/team': typeof AppTeamRoute
  '/app/transmission': typeof AppTransmissionRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/account': typeof AppAccountRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/hospital-map': typeof AppHospitalMapRoute
  '/app/lab': typeof AppLabRoute
  '/app/outbreaks': typeof AppOutbreaksRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/pipelines': typeof AppPipelinesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resistance': typeof AppResistanceRoute
  '/app/screening': typeof AppScreeningRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/surveillance': typeof AppSurveillanceRoute
  '/app/team': typeof AppTeamRoute
  '/app/transmission': typeof AppTransmissionRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/account': typeof AppAccountRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/hospital-map': typeof AppHospitalMapRoute
  '/app/lab': typeof AppLabRoute
  '/app/outbreaks': typeof AppOutbreaksRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/pipelines': typeof AppPipelinesRoute
  '/app/reports': typeof AppReportsRoute
  '/app/resistance': typeof AppResistanceRoute
  '/app/screening': typeof AppScreeningRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/surveillance': typeof AppSurveillanceRoute
  '/app/team': typeof AppTeamRoute
  '/app/transmission': typeof AppTransmissionRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/app/account'
    | '/app/admin'
    | '/app/alerts'
    | '/app/devices'
    | '/app/forecasting'
    | '/app/hospital-map'
    | '/app/lab'
    | '/app/outbreaks'
    | '/app/patients'
    | '/app/pipelines'
    | '/app/reports'
    | '/app/resistance'
    | '/app/screening'
    | '/app/settings'
    | '/app/surveillance'
    | '/app/team'
    | '/app/transmission'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/account'
    | '/app/admin'
    | '/app/alerts'
    | '/app/devices'
    | '/app/forecasting'
    | '/app/hospital-map'
    | '/app/lab'
    | '/app/outbreaks'
    | '/app/patients'
    | '/app/pipelines'
    | '/app/reports'
    | '/app/resistance'
    | '/app/screening'
    | '/app/settings'
    | '/app/surveillance'
    | '/app/team'
    | '/app/transmission'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/app'
    | '/app/account'
    | '/app/admin'
    | '/app/alerts'
    | '/app/devices'
    | '/app/forecasting'
    | '/app/hospital-map'
    | '/app/lab'
    | '/app/outbreaks'
    | '/app/patients'
    | '/app/pipelines'
    | '/app/reports'
    | '/app/resistance'
    | '/app/screening'
    | '/app/settings'
    | '/app/surveillance'
    | '/app/team'
    | '/app/transmission'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/transmission': {
      id: '/app/transmission'
      path: '/transmission'
      fullPath: '/app/transmission'
      preLoaderRoute: typeof AppTransmissionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/surveillance': {
      id: '/app/surveillance'
      path: '/surveillance'
      fullPath: '/app/surveillance'
      preLoaderRoute: typeof AppSurveillanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/screening': {
      id: '/app/screening'
      path: '/screening'
      fullPath: '/app/screening'
      preLoaderRoute: typeof AppScreeningRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/resistance': {
      id: '/app/resistance'
      path: '/resistance'
      fullPath: '/app/resistance'
      preLoaderRoute: typeof AppResistanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pipelines': {
      id: '/app/pipelines'
      path: '/pipelines'
      fullPath: '/app/pipelines'
      preLoaderRoute: typeof AppPipelinesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/outbreaks': {
      id: '/app/outbreaks'
      path: '/outbreaks'
      fullPath: '/app/outbreaks'
      preLoaderRoute: typeof AppOutbreaksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/lab': {
      id: '/app/lab'
      path: '/lab'
      fullPath: '/app/lab'
      preLoaderRoute: typeof AppLabRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/hospital-map': {
      id: '/app/hospital-map'
      path: '/hospital-map'
      fullPath: '/app/hospital-map'
      preLoaderRoute: typeof AppHospitalMapRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/forecasting': {
      id: '/app/forecasting'
      path: '/forecasting'
      fullPath: '/app/forecasting'
      preLoaderRoute: typeof AppForecastingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/devices': {
      id: '/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppForecastingRoute: typeof AppForecastingRoute
  AppHospitalMapRoute: typeof AppHospitalMapRoute
  AppLabRoute: typeof AppLabRoute
  AppOutbreaksRoute: typeof AppOutbreaksRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPipelinesRoute: typeof AppPipelinesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResistanceRoute: typeof AppResistanceRoute
  AppScreeningRoute: typeof AppScreeningRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSurveillanceRoute: typeof AppSurveillanceRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTransmissionRoute: typeof AppTransmissionRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppForecastingRoute: AppForecastingRoute,
  AppHospitalMapRoute: AppHospitalMapRoute,
  AppLabRoute: AppLabRoute,
  AppOutbreaksRoute: AppOutbreaksRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPipelinesRoute: AppPipelinesRoute,
  AppReportsRoute: AppReportsRoute,
  AppResistanceRoute: AppResistanceRoute,
  AppScreeningRoute: AppScreeningRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSurveillanceRoute: AppSurveillanceRoute,
  AppTeamRoute: AppTeamRoute,
  AppTransmissionRoute: AppTransmissionRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
