/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTransmissionRouteImport } from './routes/app/transmission'
import { Route as AppSurveillanceRouteImport } from './routes/app/surveillance'
import { Route as AppScreeningRouteImport } from './routes/app/screening'
import { Route as AppResistanceRouteImport } from './routes/app/resistance'
import { Route as AppPipelinesRouteImport } from './routes/app/pipelines'
import { Route as AppPatientsRouteImport } from './routes/app/patients'
import { Route as AppOutbreaksRouteImport } from './routes/app/outbreaks'
import { Route as AppHospitalMapRouteImport } from './routes/app/hospital-map'
import { Route as AppForecastingRouteImport } from './routes/app/forecasting'
import { Route as AppDevicesRouteImport } from './routes/app/devices'
import { Route as AppAlertsRouteImport } from './routes/app/alerts'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTransmissionRoute = AppTransmissionRouteImport.update({
  id: '/transmission',
  path: '/transmission',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSurveillanceRoute = AppSurveillanceRouteImport.update({
  id: '/surveillance',
  path: '/surveillance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScreeningRoute = AppScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResistanceRoute = AppResistanceRouteImport.update({
  id: '/resistance',
  path: '/resistance',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPipelinesRoute = AppPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPatientsRoute = AppPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOutbreaksRoute = AppOutbreaksRouteImport.update({
  id: '/outbreaks',
  path: '/outbreaks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHospitalMapRoute = AppHospitalMapRouteImport.update({
  id: '/hospital-map',
  path: '/hospital-map',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppForecastingRoute = AppForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/hospital-map': typeof AppHospitalMapRoute
  '/app/outbreaks': typeof AppOutbreaksRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/pipelines': typeof AppPipelinesRoute
  '/app/resistance': typeof AppResistanceRoute
  '/app/screening': typeof AppScreeningRoute
  '/app/surveillance': typeof AppSurveillanceRoute
  '/app/transmission': typeof AppTransmissionRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/hospital-map': typeof AppHospitalMapRoute
  '/app/outbreaks': typeof AppOutbreaksRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/pipelines': typeof AppPipelinesRoute
  '/app/resistance': typeof AppResistanceRoute
  '/app/screening': typeof AppScreeningRoute
  '/app/surveillance': typeof AppSurveillanceRoute
  '/app/transmission': typeof AppTransmissionRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/alerts': typeof AppAlertsRoute
  '/app/devices': typeof AppDevicesRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/hospital-map': typeof AppHospitalMapRoute
  '/app/outbreaks': typeof AppOutbreaksRoute
  '/app/patients': typeof AppPatientsRoute
  '/app/pipelines': typeof AppPipelinesRoute
  '/app/resistance': typeof AppResistanceRoute
  '/app/screening': typeof AppScreeningRoute
  '/app/surveillance': typeof AppSurveillanceRoute
  '/app/transmission': typeof AppTransmissionRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/alerts'
    | '/app/devices'
    | '/app/forecasting'
    | '/app/hospital-map'
    | '/app/outbreaks'
    | '/app/patients'
    | '/app/pipelines'
    | '/app/resistance'
    | '/app/screening'
    | '/app/surveillance'
    | '/app/transmission'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/alerts'
    | '/app/devices'
    | '/app/forecasting'
    | '/app/hospital-map'
    | '/app/outbreaks'
    | '/app/patients'
    | '/app/pipelines'
    | '/app/resistance'
    | '/app/screening'
    | '/app/surveillance'
    | '/app/transmission'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/alerts'
    | '/app/devices'
    | '/app/forecasting'
    | '/app/hospital-map'
    | '/app/outbreaks'
    | '/app/patients'
    | '/app/pipelines'
    | '/app/resistance'
    | '/app/screening'
    | '/app/surveillance'
    | '/app/transmission'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/transmission': {
      id: '/app/transmission'
      path: '/transmission'
      fullPath: '/app/transmission'
      preLoaderRoute: typeof AppTransmissionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/surveillance': {
      id: '/app/surveillance'
      path: '/surveillance'
      fullPath: '/app/surveillance'
      preLoaderRoute: typeof AppSurveillanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/screening': {
      id: '/app/screening'
      path: '/screening'
      fullPath: '/app/screening'
      preLoaderRoute: typeof AppScreeningRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/resistance': {
      id: '/app/resistance'
      path: '/resistance'
      fullPath: '/app/resistance'
      preLoaderRoute: typeof AppResistanceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pipelines': {
      id: '/app/pipelines'
      path: '/pipelines'
      fullPath: '/app/pipelines'
      preLoaderRoute: typeof AppPipelinesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/patients': {
      id: '/app/patients'
      path: '/patients'
      fullPath: '/app/patients'
      preLoaderRoute: typeof AppPatientsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/outbreaks': {
      id: '/app/outbreaks'
      path: '/outbreaks'
      fullPath: '/app/outbreaks'
      preLoaderRoute: typeof AppOutbreaksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/hospital-map': {
      id: '/app/hospital-map'
      path: '/hospital-map'
      fullPath: '/app/hospital-map'
      preLoaderRoute: typeof AppHospitalMapRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/forecasting': {
      id: '/app/forecasting'
      path: '/forecasting'
      fullPath: '/app/forecasting'
      preLoaderRoute: typeof AppForecastingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/devices': {
      id: '/app/devices'
      path: '/devices'
      fullPath: '/app/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppDevicesRoute: typeof AppDevicesRoute
  AppForecastingRoute: typeof AppForecastingRoute
  AppHospitalMapRoute: typeof AppHospitalMapRoute
  AppOutbreaksRoute: typeof AppOutbreaksRoute
  AppPatientsRoute: typeof AppPatientsRoute
  AppPipelinesRoute: typeof AppPipelinesRoute
  AppResistanceRoute: typeof AppResistanceRoute
  AppScreeningRoute: typeof AppScreeningRoute
  AppSurveillanceRoute: typeof AppSurveillanceRoute
  AppTransmissionRoute: typeof AppTransmissionRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppDevicesRoute: AppDevicesRoute,
  AppForecastingRoute: AppForecastingRoute,
  AppHospitalMapRoute: AppHospitalMapRoute,
  AppOutbreaksRoute: AppOutbreaksRoute,
  AppPatientsRoute: AppPatientsRoute,
  AppPipelinesRoute: AppPipelinesRoute,
  AppResistanceRoute: AppResistanceRoute,
  AppScreeningRoute: AppScreeningRoute,
  AppSurveillanceRoute: AppSurveillanceRoute,
  AppTransmissionRoute: AppTransmissionRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
